---

# Main tasks file for nginx-proxy role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::nginx-proxy'
    - 'role::nginx-proxy::init'


- name: 'NGINX PROXY | Deploy Docker compose project'
  include_role:
    name: "{{ _docker_service_role_full_name }}"
  tags:
    - 'role::nginx-proxy'
    - 'role::nginx-proxy::service'
  vars:
    _ansistrano_git_repo: "{{ nginx_proxy_git_repo }}"
    _ansistrano_git_branch: "{{ nginx_proxy_git_branch }}"
    _docker_service_compose_options: "{{ nginx_proxy_compose_options }}"
    _docker_service_compose_override: "{{ nginx_proxy_compose_override }}"
    _docker_service_compose_path: "{{ nginx_proxy_compose_path }}"
    _docker_service_project_name: "{{ nginx_proxy_project_name }}"
    _docker_service_templates: "{{ nginx_proxy_templates | default([]) }}"
    _docker_service_networks: "{{ nginx_proxy_networks }}"
    _docker_service_volumes: "{{ nginx_proxy_volumes | default([]) }}"
